[package]
name = "tamago"
version = "0.0.0"
edition = "2024"

description = "Library for generating C code"
license-file = "LICENSE.txt"
authors = ["Nobuharu Shimazu <nobu.bichanna@gmail.com>"]
readme = "README.md"

[dependencies]
tamacro = { path = "tamacro" }
